// <auto-generated />
namespace VodafoneWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_changehistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_changehistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201509101226059_update_changehistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
